name: Run Pull Request Checks

on: [pull_request]

jobs:
    tests:
        name: Run Tests

        runs-on: ubuntu-latest
        strategy:
            matrix:
                runtime: [node@22, node@24, node@26]

        steps:
            - uses: actions/checkout@v7
            - name: Use ${{ matrix.runtime }}
              uses: pnpm/setup@v3
              with:
                  cache: true
                  runtime: ${{ matrix.runtime }}

            - name: Compile
              run: pnpm build:code

            - name: Tests
              run: pnpm test

    lint_and_format:
        name: Run Lint and Format
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7
            - uses: pnpm/setup@v3
              with:
                  cache: true

            - name: Linted
              run: pnpm lint

            - name: Nice
              run: pnpm prettier
