name: Run Pull Request Checks

on: [pull_request]

jobs:
    tests:
        name: Run Tests

        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x, 22.x, 24.x]

        steps:
            - uses: actions/checkout@v6
            - uses: pnpm/action-setup@v6
              with:
                  version: 10
                  cache: true
                  run_install: true
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm

            - name: Compile
              run: pnpm build:code

            - name: Tests
              run: pnpm test

    lint_and_format:
        name: Run Lint and Format
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6
            - uses: pnpm/action-setup@v6
              with:
                  version: 10
                  cache: true
                  run_install: true
            - uses: actions/setup-node@v6
              with:
                  node-version: 24.x
                  cache: pnpm

            - name: Linted
              run: pnpm lint

            - name: Nice
              run: pnpm prettier
