name: Run Pull Request Checks

on:
  pull_request:
    paths:
      - 'src/*.js'
      - 'src/messages/*.js'
      - 'tests/*.js'

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: npm ci --only=dev
      - name: Nice
        run: npm run prettier
      - name: Linted
        run: npm run lint
      - name: Tests
        run: npm run test
